// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEZW6u_2jc70caAkReCtCCUEfFbpAyFH0',
    appId: '1:1073232599336:web:1a8b8403b7937c46aa581d',
    messagingSenderId: '1073232599336',
    projectId: 'mirruldemo',
    authDomain: 'mirruldemo.firebaseapp.com',
    storageBucket: 'mirruldemo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjigwGBLPpH8vBoMvBSzsvQdA9_Szr-0',
    appId: '1:1073232599336:android:f528f7568e21b54eaa581d',
    messagingSenderId: '1073232599336',
    projectId: 'mirruldemo',
    storageBucket: 'mirruldemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJuhm8Wr1HKzNGYxxIvIXyqnrCtlDLM5E',
    appId: '1:1073232599336:ios:4c87761623ec8253aa581d',
    messagingSenderId: '1073232599336',
    projectId: 'mirruldemo',
    storageBucket: 'mirruldemo.appspot.com',
    iosClientId: '1073232599336-nrbu575kj4642dtpj700bsekhaj24o5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mirruldemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJuhm8Wr1HKzNGYxxIvIXyqnrCtlDLM5E',
    appId: '1:1073232599336:ios:4c87761623ec8253aa581d',
    messagingSenderId: '1073232599336',
    projectId: 'mirruldemo',
    storageBucket: 'mirruldemo.appspot.com',
    iosClientId: '1073232599336-nrbu575kj4642dtpj700bsekhaj24o5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mirruldemo',
  );
}
